
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmqxrtqwgzelnbzeffek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtcXhydHF3Z3plbG5iemVmZmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzEyNTMsImV4cCI6MjA1OTAwNzI1M30.VK4cvspN7AWjJTQ8FyzI2DKTustco4nTSP6CimX42Tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
